- name: "Restart MongoDB"
  service: >
    name=mongod
    state=restarted
  tags:
    - mongodb

- name: "Restart collectd"
  service: >
    name=collectd
    state=restarted
  tags:
    - mongodb
    - collectd
